### ISSUE TITLE
contact issues

### ISSUE THREAD

**Issue by Bamboooz** [smattar2020/emailpy#1]
Hey, could you please check your gmail inbox, I sent you an email, please respond.

**Comment by Bamboooz** [comment]
@3DCoded

**Comment by 3DCoded** [comment]
If you have a question about this project, please submit it as an issue here. I don't do issues over email.

**Comment by Bamboooz** [comment]
It was about a pypi project name ospy which was left for like 2 or 3 years without usage and I wanted to request that name but im not interested anymore.
